#!/bin/bash
#
# git-dude - Git commit notifier
# https://github.com/sickill/git-dude
#
# Copyright (C) 2011 Marcin Kulik <http://ku1ik.com/>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
# Distributed under the GNU General Public License, version 2.0.

interval=$(git config dude.interval)
interval=${interval:-60}

icon_path=$(git config dude.icon)
icon_path=${icon_path:-`pwd`/icon.png}
eval icon_path=$icon_path # to expand ~

export LC_ALL=C # make sure git talks english

[[ -d $1 ]] && cd $1

function notify() {
  if [ $(which notify-send 2>/dev/null) ]; then
    notify-send -i "$1" "$2" "$3"
  elif [ $(which growlnotify 2>/dev/null) ]; then
    growlnotify --image "$1" -m "$3" "$2"
  elif [ $(which kdialog 2>/dev/null) ]; then
    kdialog --icon $1 --title "$2" --passivepopup "$3"
  else
    echo $2; echo $3
  fi
}

while true; do
  for dir_name in *; do
    if [[ -d $dir_name && $(cd $dir_name; git rev-parse --git-dir 2>/dev/null) ]]; then
      repo_name=$(basename $dir_name .git)
      cd "$dir_name"

      changes=""
      if [[ $(grep svn-remote .git/config 2>/dev/null) ]]; then
        revs=$(git svn fetch 2>/dev/null | grep -F -- ' = ' | awk '{ print $3 }')
        if [[ -n "$revs" ]]; then
          changes="$(echo "$revs" | head -1)~..$(echo "$revs" | tail -1)"
        fi
      else
        changes=$(git fetch 2>&1 | grep -F -- '->')
      fi


      while read -r line; do
        case $line in
          *..*)
            commit_range=$(echo "$line" | awk '{ print $1 }')
            commit_messages=$(git log $commit_range --pretty=format:'%s (%an)')

            branch_name=$(echo "$line" | awk '{ print $2 }')
            if [[ -n "$branch_name" ]]; then
              branch_name="/$branch_name"
            fi

            notify $icon_path "New commits in $repo_name$branch_name" "$commit_messages"
            ;;

          *new\ branch*)
            branch_name=$(echo "$line" | awk '{ print $4 }')
            notify $icon_path "New branch $repo_name/$branch_name"
            ;;

          *new\ tag*)
            tag_name=$(echo "$line" | awk '{ print $4 }')
            notify $icon_path "New tag $repo_name/$tag_name"
            ;;
        esac
      done <<< "$changes"

      cd - &>/dev/null
    fi
  done

  sleep $interval
done
